### ISSUE TITLE
Use new game state: finished

### ISSUE THREAD

**Issue by robinandeer** [futu-sto-tech/gif-me-an-answer-client#31]
Relevant change: https://github.com/futu-sto-tech/gif-me-an-answer-server/commit/6fe6476137326f35e395c4d7294f02c16ffc7df9

**Comment by iensu** [comment]
Closed by https://github.com/futu-sto-tech/gif-me-an-answer-client/commit/7af1b2422bee6d139c24c2be01d2fc2b502285a2
