### ISSUE TITLE
Update code to expect 1-based order indexing

### ISSUE THREAD

**Issue by robinandeer** [futu-sto-tech/gif-me-an-answer-client#33]
New update in the backend:

https://github.com/futu-sto-tech/gif-me-an-answer-server/commit/094423c1d01887e53c7deffc7e3b6c7087b96b99

**Comment by iensu** [comment]
Closed by https://github.com/futu-sto-tech/gif-me-an-answer-client/commit/fc83b45162d0489253cb87b732ee0896727640cf
